server:
  port: 8080

spring:
  mvc:
    servlet:
      path: /api
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/jpa?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        stat: DEBUG
        SQL: DEBUG
